### PR TITLE
Add AWSSSMChaosRunner

### PR DESCRIPTION
**Pull request by neo01124**

### CODE REVIEW

**Comment by dastergon** [comment]
Hey @neo01124, thanks a lot for the PR. Can you rebase and push again?

**Comment by neo01124** [comment]
@dastergon is that fine?

**Comment by dastergon** [comment]
Hi @neo01124, can you rebase manually? because the auto-resolve introduces unnecessary commits and messes up with the history.

**Comment by neo01124** [comment]
@dastergon I created a new PR. 

This one was already manually rebased, not sure why it had a conflict for merging. Just deleted the fork and re-created the commit in https://github.com/dastergon/awesome-chaos-engineering/pull/97

**Pull request closed without merging**
