### PR TITLE
Added Chaos Monkey for Spring Boot

### PR DESCRIPTION
**Pull request by marcelbirkner**
for documentation see https://codecentric.github.io/chaos-monkey-spring-boot/

### CODE REVIEW

**Comment by marcelbirkner** [comment]
Please add chaos monkey for spring boot applications

**Comment by dastergon** [comment]
Hi @marcelbirkner,

Thanks for your contribution!. Is it possible to update the title of the hyperlink to "Chaos Monkey for Spring Boot"? 

Thanks!

**Comment by dastergon** [comment]
:+1:

**Comment by marcelbirkner** [comment]
Thank you :-)

**Pull request merged**
